In [1]:
import numpy as np

In [2]:
%%writefile quasm_module.py

def load_qasm_file(filename):
    '''
    Reads in a .qasm file. filename a string with the filename, eg. 'test1.qasm'
    ---
    Return: List of strings with all characters in the file
    '''
    quasm_file=[]
    f=open(filename,'r')
    for line in f:
        quasm_file.append(line)
    return quasm_file

def get_filtered_qasm(list_of_qasm_strings):
    '''
    In: List of strings with comments
    ---
    Return: list of strings without comments
    '''
    quasm_instrunctions=[]
    alphabet='abcdefghijklmnopqrstuvwxyz'
    m=0
    for tt, line in enumerate(list_of_qasm_strings):
        if not line[0] in alphabet:
            m+=1
            pass
        else:
            quasm_instrunctions.append('')
            for char in line:
                if not char=='#':
                    quasm_instrunctions[tt-m]+=char
                else:
                    break
    return quasm_instrunctions

def number_of_qubits(quasm_instrunctions):
    '''
    In: filtered quasm instructions
    ---
    Out: integer with number of needed qubits
    '''
    num_qubits=0
    for line in quasm_instrunctions:
        if 'qubit' in line:
            num_qubits+=1
    return num_qubits

Overwriting quasm_module.py


In [3]:
import quasm_module as qm

In [10]:
bla=qm.load_qasm_file('test1.qasm')

In [11]:
instructions=qm.get_filtered_qasm(bla)

In [12]:
instructions

['qubit   q0  ', 'h   q0      ', 'measure q0  ']

In [3]:
filename='test1.qasm'
quasm_file=[]
f=open(filename,'r')
for line in f:
    quasm_file.append(line)
    print(line)



qubit   q0  # Define a qubit

h   q0      # Apply a Hadamard gate

measure q0  # Measure in computational basis



In [20]:
quasm_instrunctions=[]
alphabet='abcdefghijklmnopqrstuvwxyz'
m=0
for tt, line in enumerate(quasm_file):
    if not line[0] in alphabet:
        m+=1
        pass
    else:
        quasm_instrunctions.append('')
        for char in line:
            if not char=='#' or char=='\n':
                quasm_instrunctions[tt-m]+=char
            else:
                break
print(quasm_instrunctions)
            

['qubit   q0  ', 'h   q0      ', 'measure q0  ']


In [13]:
num_qubits=0
for line in quasm_instrunctions:
    if 'qubit' in line:
        num_qubits+=1
print('Number of qubits is '+str(num_qubits))

Number of qubits is 1


In [11]:
def number_of_qubits(quasm_instrunctions):
    num_qubits=0
    for line in quasm_instrunctions:
        if 'qubit' in line:
            num_qubits+=1
    return num_qubits

1

In [45]:
np.tensordot([[0,1],[0,1]],[[0,1],[0,1]])

array(2)

In [52]:
A=np.array([[1,0],[0,1]])
print(A)
B=np.array([[1,0],[1,1]])
print(B)
print(np.kron(A,B))

[[1 0]
 [0 1]]
[[1 0]
 [1 1]]
[[1 0 0 0]
 [1 1 0 0]
 [0 0 1 0]
 [0 0 1 1]]


In [47]:
np.outer([[1,0],[0,1]],[[0,1],[0,1]])

array([[0, 1, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 1]])

### Basic Ideas
* Read in the quasm file
* Extract such that it contains only relevant information
* Make a qubit class
* Find how many quibts are needed
